name: OpenSSF Scorecard

on:
  schedule:
    - cron: '0 6 * * 1'
  push:
    branches: [ "main", "v4" ]
  workflow_dispatch:

permissions:
  security-events: write
  contents: read
  actions: read

jobs:
  analysis:
    uses: kubestellar/infra/.github/workflows/reusable-scorecard.yml@dd836e89cb97c6e433067497ebcb355a01741aad # kubestellar/infra main as of 2026-09-01
